global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "python-fixed-time-api"
    static_configs:
      - targets: ["python-fixed-time-api:8000"]

  - job_name: "go-fixed-time-api"
    static_configs:
      - targets: ["go-fixed-time-api:8080"]

  - job_name: "metrics-collector"
    static_configs:
      - targets: ["localhost:9090"]
